=== RushuiGuan/framework/codegen/test-client/codegen-settings.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CodeGenSettings",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "typeScriptWebClientSettings": {
      "$ref": "#/definitions/TypeScriptWebClientSettings"
    },
    "cSharpWebClientSettings": {
      "$ref": "#/definitions/CSharpWebClientSettings"
    },
    "apiControllerConversionSetting": {
      "$ref": "#/definitions/ApiControllerConversionSettings"
    },
    "controllerFilter": {
      "$ref": "#/definitions/SymbolFilterPatterns"
    },
    "dtoFilter": {
      "$ref": "#/definitions/SymbolFilterPatterns"
    },
    "enumFilter": {
      "$ref": "#/definitions/SymbolFilterPatterns"
    },
    "controllerMethodFilters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SymbolFilterPatterns"
      }
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "TypeScriptWebClientSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "controllerFilter": {
          "$ref": "#/definitions/SymbolFilterPatterns"
        },
        "controllerMethodFilters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SymbolFilterPatterns"
          }
        },
        "dtoFilter": {
          "$ref": "#/definitions/SymbolFilterPatterns"
        },
        "enumFilter": {
          "$ref": "#/definitions/SymbolFilterPatterns"
        },
        "endPointName": {
          "type": "string"
        },
        "baseClassName": {
          "type": "string"
        },
        "baseClassModule": {
          "type": "string"
        },
        "configServiceModule": {
          "type": "string"
        },
        "usePromise": {
          "type": "boolean"
        },
        "entryFile": {
          "type": "string"
        },
        "sourcePathRelatedToEntryFile": {
          "type": "string"
        },
        "nameSpaceModuleMapping": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "baseTypeMapping": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "SymbolFilterPatterns": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "exclude": {
          "type": [
            "null",
            "string"
          ]
        },
        "include": {
          "type": [
            "null",
            "string"
          ]
        },
        "hasValue": {
          "type": "boolean"
        }
      }
    },
    "CSharpWebClientSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "controllerFilter": {
          "$ref": "#/definitions/SymbolFilterPatterns"
        },
        "controllerMethodFilters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SymbolFilterPatterns"
          }
        },
        "namespace": {
          "type": "string"
        },
        "useTextContentTypeForStringPost": {
          "type": "boolean"
        },
        "useInterface": {
          "type": "boolean"
        },
        "useInternalProxy": {
          "type": "boolean"
        }
      }
    },
    "ApiControllerConversionSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "globalMethodSettings": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/WebClientMethodSettings"
            }
          ]
        },
        "methodSettings": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/WebClientMethodSettings"
          }
        }
      }
    },
    "WebClientMethodSettings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "useDateTimeAsDateOnly": {
          "type": [
            "boolean",
            "null"
          ]
        }
      }
    }
  }
}

=== RushuiGuan/framework/codegen/Test.WithInterface.Proxy/codegen-settings.json
{
	"$schema": "codegen-settings.schema.json",
	"typeScriptWebClientSettings": {
		"nameSpaceModuleMapping": {
			"Test.Dto.Enums": "enum.generated.ts",
			"Test.Dto.Classes": "dto.generated.ts"
		},
		"controllerMethodFilters": [
			{
				"exclude": "FilteredByTypeScript$"
			}
		],
		"endPointName": "test-client",
		"baseClassModule": "@mirage/webclient",
		"configServiceModule": "@mirage/config",
		"usePromise": false
	},
	"cSharpWebClientSettings": {
		"namespace": "Test.WithInterface.Proxy",
		"controllerMethodFilters": [
			{
				"exclude": "FilteredByCSharp$"
			}
		],
		"useInterface": true,
		"useInternalProxy": false
	},
	"apiControllerConversionSetting": {
		"globalMethodSettings": {
			"useDateTimeAsDateOnly": false
		},
		"methodSettings": {
			"FromRouteParamTestController.DateTimeAsDateOnlyRoute": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnlyCollection": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnlyArray": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnly": {
				"useDateTimeAsDateOnly": true
			}
		}
	},
	"controllerFilter": {
		"exclude": "^Test\\.WebApi\\.Controllers\\.(AbsUrl)?RedirectTestController$"
	},
	"controllerMethodFilters": [
		{ "exclude": "FilteredByAll$" }
	]
}

=== RushuiGuan/framework/codegen/test-client/codegen-settings.json
{
	"$schema": "codegen-settings.schema.json",
	"typeScriptWebClientSettings": {
		"nameSpaceModuleMapping": {
			"Test.Dto": "dto.generated.ts"
		},
		"controllerMethodFilters": [
			{
				"exclude": "FilteredByTypeScript$"
			}
		],
		"endPointName": "test-client",
		"baseClassModule": "@mirage/webclient",
		"configServiceModule": "@mirage/config",
		"usePromise": false,
		"baseTypeMapping": {
			"Test.Dto.Classes.AbstractClass":"MyBaseClass,./dto",
			"Test.Dto.Classes.ICommand":"ICommand,./dto"
		}
	},
	"apiControllerConversionSetting": {
		"globalMethodSettings": {
			"useDateTimeAsDateOnly": false
		},
		"methodSettings": {
			"FromRouteParamTestController.DateTimeAsDateOnlyRoute": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnlyCollection": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnlyArray": {
				"useDateTimeAsDateOnly": true
			},
			"RequiredParamTestController.RequiredDateTimeAsDateOnly": {
				"useDateTimeAsDateOnly": true
			}
		}
	},
	"controllerFilter": {
		"exclude": "^Test\\.WebApi\\.Controllers\\.(AbsUrl)?RedirectTestController$"
	},
	"controllerMethodFilters": [
		{ "exclude": "FilteredByAll$" }
	]
}
